name: Scheduled HTTP Request

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行

jobs:
  run-http-request:
    runs-on: ubuntu-latest
    steps:
    - name: Curl HTTP Request
      run: curl -X POST http://rboy.xyz/api.php/timming/index.html?enforce=1&name=
